const answers = {
    {name: 'Mudbricks and mortar', year: -9000},
    {name: 'Alcohol Fermentation', year: -7000},
    {name: 'Dog sleds', year: -7000},
    {name: 'Tanned leather', year: -7000},
    {name: 'Lead smelting', year: -6500},
    {name: 'Kilns', year: -6000},
    {name: 'Copper smelting', year: -5000},
    {name: 'Seawalls', year: -5000},
    {name: 'Cotton thread', year: -5000},
    {name: 'Iron smelting', year: -1300},
    {name: 'Saddle', year: -700},
    {name: 'Crossbow', year: -650},
    {name: 'Coins', year: -600},
    {name: 'Lighthouse', year: -500},
    {name: 'Catapult', year: -485},
    {name: 'Scythed chariot', year: -485},
    {name: 'Oil wells', year: 347},
    {name: 'Sulfur matches', year: 577},
    {name: 'Toilet paper', year: 589},
    {name: 'Windmill', year: 650},
    {name: 'Movable Type', year: 1088},
    {name: 'Land mines', year: 1277},
    {name: 'Eyeglasses', year: 1286},
    {name: 'Printing press', year: 1439},
    {name: 'Floating dock', year: 1560},
    {name: 'Mercator projection map', year: 1569},
    {name: 'Newspaper', year: 1605},
    {name: 'Telescope', year: 1608},
    {name: 'Slide rule', year: 1630}
    {name: 'Mechanical calculator', year: 1642},
    {name: 'Barometer', year: 1643},
    {name: 'Vacuum pump', year: 1650},
    {name: 'Pendulum clock', year: 1656},
    {name: 'Alcohol thermometer', year: 1709},
    {name: 'Steam engine', year: 1698},
    {name: 'Mechanized cotton spinning machine', year: 1738},
    {name: 'Lighting rod', year: 1752},
    {name: 'Artificial refrigerator', year: 1755},
    {name: 'Spinning jenny', year: 1764},
    {name: 'Water carbonation', year: 1767},
    {name: 'Weighing scale', year: 1770},
    {name: 'Screw-cutting lathe', year: 1775},
    {name: 'Mechanical air compressor', year: 1776},
    {name: 'Steamboat', year: 1783},
    {name: 'Hot air balloon', year: 1783},
    {name: 'Parachute', year: 1783},
    {name: 'Electrolysis', year: 1785},
    {name: 'Threshing machine', year: 1786},
    {name: 'Power loom', year: 1789},
    {name: 'Sewing machine', year: 1790},
    {name: 'Telegraph', year: 1792},
    {name: 'Cotton gin', year: 1793},
    {name: 'Hydraulic press', year: 1795},
    {name: 'Lithography printing', year: 1796},
    {name: 'Plywood', year: 1797},
    {name: 'Vaccine', year: 1798},
    {name: 'Motorized air compressor', year: 1799},
    {name: 'Morphine', year: 1804},
    {name: 'Steam locomotive', year: 1804},
    {name: 'General anesthetic', year: 1804},
    {name: 'Food canning', year: 1810},
    {name: 'Wristwatch', year: 1810},
    {name: 'Photography', year: 1822},
    {name: 'First programmable mechanical computer', year: 1822},
    {name: 'Lighter', year: 1823},
    {name: 'Bolt-action rifle', year: 1824},
    {name: 'Electromagnet', year: 1825},
    {name: 'Friction match', year: 1826},
    {name: 'Gas stove', year: 1826},
    {name: 'Reaping machine', year: 1828},
    {name: 'Compound air compressor', year: 1829},
    {name: 'Lawn mower', year: 1830},
    {name: 'First practical electric motor', year: 1834},
    {name: 'Electromechanical relay', year: 1835},
    {name: 'Morse code', year: 1837},
    {name: 'Electrotyping', year: 1838},
    {name: 'Steam shovel', year: 1839},
    {name: 'Steam hammer', year: 1839},
    {name: 'Solar cell', year: 1839},
    {name: 'Fuel cell', year: 1842},
    {name: 'Man-made fertilizer', year: 1842},
    {name: 'Wood pulp paper production', year: 1844},
    {name: 'Cement', year: 1845},
    {name: 'Tunnel boring machine', year: 1846},
    {name: 'Nitroglycerin', year: 1847},
    {name: 'Pneumatic drill', year: 1848},
    {name: 'Public flush toilet', year: 1851},
    {name: 'Safety brake elevator', year: 1852},
    {name: 'Manned flight in a dirigible', year: 1852},
    {name: 'Reinforced concrete', year: 1853},
    {name: 'Practical color photography', year: 1855},
    {name: 'First man-made plastic', year: 1856},
    {name: 'First synthetic dye', year: 1856},
    {name: 'First rechargeable battery', year: 1859},
    {name: 'Carbon fibers', year: 1860},
    {name: 'Pasteurization', year: 1864},
    {name: 'Dynamite', year: 1867},
    {name: 'Barbed wire', year: 1867},
    {name: 'Stainless steel', year: 1872},
    {name: 'Rotary kiln', year: 1873},
    {name: 'First commercial electrical generator', year: 1873},
    {name: 'Metal detector', year: 1874},
    {name: 'Electric tram', year: 1875},
    {name: 'Telephone', year: 1876},
    {name: 'Phonograph', year: 1877},
    {name: 'Rebreather', year: 1878},
    {name: 'Incandescent lightbulb', year: 1879},
    {name: 'Arc welding', year: 1881},
    {name: 'Smokeless firearm powder', year: 1884},
    {name: 'Modern steam turbine', year: 1884},
    {name: 'Alternating Current', year: 1884},
    {name: 'Modern bicycle', year: 1885},
    {name: 'Dry cell battery', year: 1886},
    {name: 'Gasoline powered car', year: 1886},
    {name: 'Wind turbine', year: 1887},
    {name: 'Ballpoint pen', year: 1888},
    {name: 'Chlorofluorocarbons', year: 1890s},
    {name: 'Pre-cut Cardboard box', year: 1890},
    {name: 'Zipper', year: 1891},
    {name: 'Cinematograph', year: 1892},
    {name: 'Electric Oven', year: 1892},
    {name: 'Diesel engine', year: 1893},
    {name: 'Wireless communication with radio waves', year: 1895},
    {name: 'X-ray', year: 1895},
    {name: 'Polyethylene', year: 1898},
    {name: 'Nickel-cadmium battery', year: 1899},
    {name: 'Zeppelin', year: 1900},
    {name: 'Vacuum cleaner', year: 1901},
    {name: 'Gas turbine', year: 1903},
    {name: 'Airplane/first powered flight', year: 1903},
    {name: 'Vacuum tube', year: 1904},
    {name: 'Rotary-wing aircraft', year: 1907},
    {name: 'Cellophane', year: 1908},
    {name: 'Television broadcast', year: 1909},
    {name: 'Military tanks', year: 1915},
    {name: 'Liquid-fuel rocket', year: 1926},
    {name: 'Penicillin', year: 1928},
    {name: 'Jet engine', year: 1928},
    {name: 'Commercial television', year: 1928},
    {name: 'Electron microscope', year: 1931},
    {name: 'FM radio', year: 1933},
    {name: 'Nylon', year: 1935},
    {name: 'First freely programmable computer', year: 1938},
    {name: 'Nuclear fission', year: 1938},
    {name: 'Defibrillator', year: 1939},
    {name: 'Polyester', year: 1941},
    {name: 'Long-range ballistic missile', year: 1942},
    {name: 'Non-infectious viral vaccine', year: 1944},
    {name: 'Microwave oven', year: 1945},
    {name: 'Ejector seat', year: 1946},
    {name: 'Hydraulic fracking', year: 1947},
    {name: 'Transistor', year: 1947},
    {name: 'Atomic clock', year: 1948},
    {name: 'First video game', year: 1950},
    {name: 'Commercial nuclear power', year: 1951},
    {name: 'Thermonuclear weapons', year: 1952},
    {name: 'Video tape recorder', year: 1953},
    {name: 'Solar power battery', year: 1954},
    {name: 'Hovercraft', year: 1955},
    {name: 'Hard drive', year: 1956},
    {name: 'Personal computer with a keyboard', year: 1957},
    {name: 'First artificial satellite', year: 1957},
    {name: 'MOSFET transistor', year: 1959},
    {name: 'Laser', year: 1960},
    {name: 'Crewed spaceflight', year: 1961},
    {name: 'Electronic cigarette', year: 1963},
    {name: 'Commercial high-speed rail', year: 1964},
    {name: 'Kevlar', year: 1965},
    {name: 'ARPANET', year: 1969},
    {name: 'Public-key cryptography', year: 1970s},
    {name: 'Pocket calculator', year: 1970},
    {name: 'Email', year: 1971},
    {name: 'Single-chip microprocessor', year: 1971},
    {name: 'First space station', year: 1971},
    {name: 'First video game console', year: 1972},
    {name: 'Fiber optic communication', year: 1973},
    {name: 'Graphical User Interfaces', year: 1973},
    {name: 'Capacitive touchscreen', year: 1973},
    {name: 'First independent self-driving car', year: 1977},
    {name: 'Global Positioning System (GPS)', year: 1978},
    {name: 'First handheld game console', year: 1979},
    {name: 'Flash memory', year: 1980},
    {name: 'Space shuttle', year: 1981},
    {name: 'CD-ROM', year: 1982},
    {name: 'Satellite TV', year: 1982},
    {name: 'Laptop', year: 1982},
    {name: '3D printing', year: 1983},
    {name: 'Commercial cell phone', year: 1984},
    {name: 'DNA profiling', year: 1983},
    {name: 'Lithium-ion battery', year: 1985},
    {name: 'MP3 audio format', year: 1989},
    {name: 'World Wide Web', year: 1990},
    {name: 'Solid State Drive', year: 1991},
    {name: 'Mosaic, first web browser', year: 1993},
    {name: 'First smartphone', year: 1994},
    {name: 'Bluetooth', year: 1994},
    {name: 'DVD', year: 1995},
    {name: 'First wiki website', year: 1995},
    {name: 'MP3 player', year: 1998},
    {name: 'Blu-ray', year: 2000},
    {name: 'iPhone', year: 2007},
    {name: 'Blockchain', year: 2008},
    {name: 'Bitcoin', year: 2008},
    {name: 'Solar sail spacecraft', year: 2010},
    {name: 'First synthetic organism', year: 2010},
    {name: 'Commercial quantum computing', year: 2019},
    {name: 'RNA vaccine', year: 2020},
];
